### PR TITLE
Fix folding level 5+6 headings & improve fold text (lines + %)

### PR DESCRIPTION
**Pull request by myii**
@matcatc Thanks for this, I've been using it for a few years now, as you can see from the commit dates!  I was always meaning to push these through.  Just got reminded of this when suggesting this plugin to someone else.

### CODE REVIEW

**Comment by myii** [comment]
For clarity, with an input of:

```adoc
= H1

...

== H2

...

=== H3

...

==== H4

...

===== H5

...

====== H6

...

```

Folding example (current):

```vim
=== H4 [11 lines]
```

* Includes the `H5` and `H6` lines as well.

Folding example (with this PR):

```vim
==== [12.5%] H4 [3/24 lines]
```

**Comment by whnr** [comment]
That's really nice! I just wanted to work on some of the same issues!
I hope it gets merged soon!

**Comment by myii** [comment]
@whnr Thanks for the comments.  Hope it is useful for you.

**Comment by matcatc** [comment]
Nice work! I tried it out on a few of my own asciidoc files and it worked well. Thank you for contributing. Your comment showing what it does was especially useful.

**Comment by myii** [comment]
@matcatc You're welcome.  I use Asciidoctor extensively so this plugin has been really important to me.  Thanks for sharing it with us.

**Pull request merged**
